name: CI/CD for bake_forecast

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint-static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Display Python version and location
        run: |
          python --version
          whick python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Static type and security checks
        run: |
          mypy src/
    